### ISSUE TITLE
Editing a Food Review as a Customer

### ISSUE THREAD

**Issue by cyalbino** [MarPaulPalacio/CMSC-127-Best-Group-AVP#14]

**Comment by MarPaulPalacio** [comment]
Working Branch: Mar
Commit: 06631cf
Status: Finished
Remarks:

- I added a navbar for all reviews and the reviews made by the user
- The review should be made by the user to be updated and is only updated in the your reviews section.
-  I based my code on how reviews are added and only changed the query
