### ISSUE TITLE
Editing an Establishment Review as a Customer

### ISSUE THREAD

**Issue by cyalbino** [MarPaulPalacio/CMSC-127-Best-Group-AVP#15]

**Comment by MarPaulPalacio** [comment]
Working Branch: Mar
Commit: 18805f8
Status: Almost Finished
Remarks:

- I added a navbar for all reviews and the reviews made by the user
- The review should be made by the user to be updated and is only updated in the your reviews section.
-  I based my code on how reviews are added and only changed the query
- the review section still cannot be updated

**Comment by MarPaulPalacio** [comment]
Working Branch: Mar
Commit: d2a073f
Status: Finished
Remarks:

- Made review reflective, I based my establishment review html from my food review html to remove the error
