### ISSUE TITLE
Deleting a Food or Establishment Review as a Customer

### ISSUE THREAD

**Issue by cyalbino** [MarPaulPalacio/CMSC-127-Best-Group-AVP#16]

**Comment by MarPaulPalacio** [comment]
Working Branch: Mar
Commit: 06631cf
Status: Finished
Remarks:

- I added a navbar for all reviews and the reviews made by the user
- The review should be made by the user to be deleted and is only deletable in the your reviews section in the sub navbar
-  I based my code on how delete establishments are done.
