### ISSUE TITLE
See All Food Reviews of a Food Item 

### ISSUE THREAD

**Issue by cyalbino** [MarPaulPalacio/CMSC-127-Best-Group-AVP#17]

**Comment by JamesVillarosa** [comment]
Working Branch: Villarosa
Commit: 493f93a
Status: Finished
Remarks: 
- Added view_food_reviews() function on the app.py
- Added FoodReviews.html file
- Added "View all reviews" Hyperlink and changed how foods are displayed in ViewFood.html
Note: I deleted the else part in ViewFood.html but I refactor it on commit f5156e5.
