### ISSUE TITLE
See All Establishment Reviews of an Establishment

### ISSUE THREAD

**Issue by cyalbino** [MarPaulPalacio/CMSC-127-Best-Group-AVP#18]

**Comment by JamesVillarosa** [comment]
Working Branch: Villarosa
Commit: aaba733
Status: Finished
Remarks: 
- Added view_establishment_reviews() function on the app.py
- Added EstablishmentReviews.html file
- Added "View all reviews" Hyperlink in ViewEst.html
Note: Viewing reviews can catch whether there is an establishment review or not.
